# 服务端口
server:
  port: 18081
# spring相关配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=UTF-8
  main:
    banner-mode: off
  security:
    user:
      name: root
      password: root
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    banner: false
